- name: play-1 Install python3 & docker 
  #hosts: my_ec2
  hosts: all
  become: yes
  tasks: 
  - name: play-1--task-1 install docker 
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum:
      name:
      - python
      - python3
      - pip
      - docker
      - httpd
      - vim
      - net-tools
      #- mysql-server
      - mysql
      update_cache: yes
      state: present
  - name: start & enable httpd
    systemd: 
      name: httpd
      state: started
      enabled: true   
  - name: Install the php remote repo
    ansible.builtin.dnf:
      name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'
      state: present
      disable_gpg_check: true
  # - name: Install the nginx rpm from a remote repo
  #   ansible.builtin.dnf:
  #     name: 'https://rpms.remirepo.net/enterprise/remi-release-8.rpm'
  #     state: present 
  #     disable_gpg_check: true
  - name : enable dnf module enable php
    command: dnf module -y enable php
  - name: Install the latest version of Apache from the testing repo
    ansible.builtin.dnf:
      name:
      - php 
      - php-cli 
      - php-common
      - php-mysqlnd
  - name: Copy docker compose file 
    copy:
      src: /home/ahmed/Desktop/terraform/grad-proj/redhat/html_files/
      dest: /var/www/html/
  - name: Set a hostname
    ansible.builtin.hostname:
      name: http      
  - name: Reload service httpd, in all cases
    ansible.builtin.systemd:
      name: httpd.service
      state: restarted

  # - name: Put SELinux in permissive mode, logging actions that would be blocked.
  #   ansible.posix.selinux:
  #     policy: targeted
  #     state: permissive

# setenforc 0
# Modify the database address in addcontact.php man 